/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SalesManager;

import Business.Enterprise.Enterprise;
import Business.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Dhaval
 */
public class SalesManagerJPanel extends javax.swing.JPanel {
JPanel userProcessContainer;
UserAccount user;
Enterprise enterprise;
    /**
     * Creates new form SalesManagerJPanel
     */
    public SalesManagerJPanel(JPanel userProcessContainer, UserAccount user) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.user = user;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnViewQueue = new javax.swing.JButton();
        btnMyWork = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setText("SALES MANAGER WORK AREA");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnViewQueue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnViewQueue.setText("View Work Queue");
        btnViewQueue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewQueueActionPerformed(evt);
            }
        });
        add(btnViewQueue, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 220, -1));

        btnMyWork.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMyWork.setText("My Shippment Requests");
        btnMyWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyWorkActionPerformed(evt);
            }
        });
        add(btnMyWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewQueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewQueueActionPerformed
        // TODO add your handling code here:
        JPanel panel = new OrganizationWorkQueueJPanel(userProcessContainer, user);
        userProcessContainer.add("OrganizationWorkQueueJPanel", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewQueueActionPerformed

    private void btnMyWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyWorkActionPerformed
        // TODO add your handling code here:
        JPanel panel = new ViewMyWorkRequestsJPanel(userProcessContainer, user);
        userProcessContainer.add("ViewWorkQueueJPanel", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnMyWorkActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMyWork;
    private javax.swing.JButton btnViewQueue;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
