/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Business;
import Business.ConfigureBusiness;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Dhaval
 */
public class MainJFrame extends javax.swing.JFrame {
Business business;
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        //business = ConfigureBusiness.initialize();

        business = Db4o.Db4oUtil.getBusiness();
        business.setStaticVariables();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        LoginJPanel = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        passwordJField = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        LoginJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblLogin.setText("LOGIN");
        LoginJPanel.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 27, -1, -1));

        lblUserName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblUserName.setText("User Name");
        LoginJPanel.add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 62, 104, -1));

        lblPassword.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPassword.setText("Password");
        LoginJPanel.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 133, 93, -1));

        txtUserName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtUserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserNameFocusLost(evt);
            }
        });
        LoginJPanel.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 126, -1));

        passwordJField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        passwordJField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordJFieldFocusLost(evt);
            }
        });
        LoginJPanel.add(passwordJField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 168, 126, -1));

        btnLogin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        LoginJPanel.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 209, -1, -1));

        btnLogout.setText("<< Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        LoginJPanel.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jSplitPane1.setLeftComponent(LoginJPanel);

        userProcessContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(userProcessContainer);

        getContentPane().add(jSplitPane1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserNameFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_txtUserNameFocusLost

    private void passwordJFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordJFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordJFieldFocusLost

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:

        if(!Validate.validateTextField(txtUserName,lblUserName,0))
        {
            return;
        }
        if(!Validate.validateTextField(passwordJField,lblPassword,0))
        {
            return;
        }
        String userName = txtUserName.getText();
        String password = String.valueOf(passwordJField.getPassword());
        UserAccount user = business.getUad().authenticate(userName,password);
        for(Network n : business.getNetworkDirectory().getNetworkList()) {
            if(user!=null){break;}
            user = n.getUad().authenticate(userName,password);
            for(Enterprise e : n.getEnterpriseDirectory().geteList())
            {
                if(user!=null){break;}
                user = e.getUad().authenticate(userName,password);
                for(Organization o : e.getOrganizationDirectory().getOrganizationList())
                {
                    if(user!=null){break;}
                    user = o.getUad().authenticate(userName,password);
                }
            }
        }
        if(user == null)
        {
            JOptionPane.showMessageDialog(null, "Wrong Credentials");
            txtUserName.setText("");
            passwordJField.setText("");
            return;
        }
        else if((user.getStatus().equals(UserAccount.SUSPENDED)))
        {
              JOptionPane.showMessageDialog(null, "User account has been suspended");
              return;
        }
            passwordJField.setVisible(false);
            lblPassword.setVisible(false);
            btnLogin.setVisible(false);
            btnLogout.setVisible(true   );
            userProcessContainer.removeAll();
            JPanel workArea = user.getRole().getWorkArea().createView(userProcessContainer,user).returnPanel();
            userProcessContainer.add("WorkArea",workArea);
            CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
            cardLayout.next(userProcessContainer);


    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        txtUserName.setText("");
        passwordJField.setText("");
        passwordJField.setVisible(true);
        lblPassword.setVisible(true);
        btnLogin.setVisible(true);
        btnLogout.setVisible(false);
        business.getStaticVariables();
        Db4o.Db4oUtil.storeObject(business);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.first(userProcessContainer);
        userProcessContainer.removeAll();
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginJPanel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPasswordField passwordJField;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
