/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BusinessAdminWorkAreaJPanel.java
 *
 * Created on Nov 2, 2012, 5:59:07 PM
 */
package UserInterface.BusinessAdmin;

import Business.Employee;
import Business.Network.Network;
import Business.Roles.NetworkAdminRole;
import Business.UserAccount;
import UserInterface.Validate;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Dhaval
 */
public class AddUserAccountJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Employee employee;
    private Network network;

    /** Creates new form BusinessAdminWorkAreaJPanel */
    public AddUserAccountJPanel(JPanel upc, Employee employee, Network network) {
        initComponents();

        userProcessContainer = upc;
        this.employee = employee;
        this.network = network;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPassword.setText("Password:");
        add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 170, -1));

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 170, -1));

        lblUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsername.setText("Username:");
        add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAdd.setText("Add User Account");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 200, -1));

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setText("Add UserAccount");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 110, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }
        // TODO add your handling code here:         userProcessContainer.remove(this);         CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();         cardLayout.previous(userProcessContainer);     }//GEN-LAST:event_btnBackActionPerformed

        private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

            if(!Validate.validateTextField(txtUsername, lblUsername,0 ))
            {
                return;
            }
            if(!Validate.validateTextField(txtPassword, lblPassword,0 ))
            {
                return;
            }
            UserAccount ua = network.getUad().newUserAccount();
            ua.setUserName(txtUsername.getText());
            ua.setPassword(txtPassword.getText());
            ua.setRole(new NetworkAdminRole());

            txtPassword.setText("");
            txtUsername.setText("");

            JOptionPane.showMessageDialog(null, "UserAccount Added");
        }

        // TODO add your handling code here:         JPanel panel = new AddEnterpriseJPanel(userProcessContainer, business, userAccount);         userProcessContainer.add("AddEnterpriseJPanel", panel);         CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();         cardLayout.next(userProcessContainer);     }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
