/*
 * ProductManagerWorkAreaJPanel.java
 *
 * Created on October 3, 2008, 8:06 AM
 */
package UserInterface.BusinessAdmin;

import Business.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Dhaval
 */
public class BusinessAdminWorkAreaJPanel extends javax.swing.JPanel {
JPanel userProcessContainer;
UserAccount user;
    /** Creates new form ProductManagerWorkAreaJPanel */
    public BusinessAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount user) {

        initComponents();
        lblWelcome.setText("Welcome : Business Admin");
        this.userProcessContainer  = userProcessContainer;
        this.user = user;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnManageNetwork = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();
        btnManageUserAccount = new javax.swing.JButton();
        btnManageNetworkAdmin = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setText("Business Admin Work Area");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        btnManageNetwork.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnManageNetwork.setText("Manage Network>>");
        btnManageNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageNetworkActionPerformed(evt);
            }
        });
        add(btnManageNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 118, -1, -1));

        lblWelcome.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblWelcome.setText("WELCOME");
        add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 250, 20));

        btnManageUserAccount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnManageUserAccount.setText("Manage Network Admin User Account>>");
        btnManageUserAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageUserAccountActionPerformed(evt);
            }
        });
        add(btnManageUserAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 216, -1, -1));

        btnManageNetworkAdmin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnManageNetworkAdmin.setText("Manage Network Admin>>");
        btnManageNetworkAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageNetworkAdminActionPerformed(evt);
            }
        });
        add(btnManageNetworkAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 167, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    private void btnManageNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageNetworkActionPerformed
        // TODO add your handling code here:
        ManageNetworkJPanel mnjp =new ManageNetworkJPanel(userProcessContainer,user);
        userProcessContainer.add("Manage network",mnjp);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);

    }//GEN-LAST:event_btnManageNetworkActionPerformed

    private void btnManageUserAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageUserAccountActionPerformed
        // TODO add your handling code here:
        ManageAdminUserAccountJPanel mauajp =new ManageAdminUserAccountJPanel(userProcessContainer,user);
        userProcessContainer.add("Manage user account",mauajp);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageUserAccountActionPerformed

    private void btnManageNetworkAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageNetworkAdminActionPerformed
        // TODO add your handling code here:
        ManageNetworkAdminJPanel mnajp =new ManageNetworkAdminJPanel(userProcessContainer,user);
        userProcessContainer.add("Manage network Admin",mnajp);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageNetworkAdminActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageNetwork;
    private javax.swing.JButton btnManageNetworkAdmin;
    private javax.swing.JButton btnManageUserAccount;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
