/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.LicensingManager;

import Business.Enterprise.Enterprise;
import Business.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Dhaval
 */
public class LicensingManagerJPanel extends javax.swing.JPanel {
JPanel userProcessContainer;
UserAccount user;
Enterprise enterprise;
    /**
     * Creates new form SalesManagerJPanel
     */
    public LicensingManagerJPanel(JPanel userProcessContainer, UserAccount user) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.user = user;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnDrugLicensing = new javax.swing.JButton();
        btnEnterpriseLicensing = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setText("LICENSING MANAGER WORK AREA");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 430, 30));

        btnDrugLicensing.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDrugLicensing.setText("Drug Licensing");
        btnDrugLicensing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrugLicensingActionPerformed(evt);
            }
        });
        add(btnDrugLicensing, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 200, -1));

        btnEnterpriseLicensing.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEnterpriseLicensing.setText("Enterprise Licensing");
        btnEnterpriseLicensing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterpriseLicensingActionPerformed(evt);
            }
        });
        add(btnEnterpriseLicensing, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 200, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDrugLicensingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrugLicensingActionPerformed
        // TODO add your handling code here:
        DrugWorkQueueJPanel organizationWorkQueueJPanel = new DrugWorkQueueJPanel(userProcessContainer, user);
        userProcessContainer.add("OrganizationWorkQueueJPanel", organizationWorkQueueJPanel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnDrugLicensingActionPerformed

    private void btnEnterpriseLicensingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterpriseLicensingActionPerformed
        // TODO add your handling code here:
        EnterpriseWorkQueueJPanel organizationWorkQueueJPanel = new EnterpriseWorkQueueJPanel(userProcessContainer, user);
        userProcessContainer.add("OrganizationWorkQueueJPanel", organizationWorkQueueJPanel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnEnterpriseLicensingActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDrugLicensing;
    private javax.swing.JButton btnEnterpriseLicensing;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
