/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DrugManager;

import Business.*;
import Business.Enterprise.ManufacturerEnterprise;
import UserInterface.Validate;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Dhaval
 */
public class AddDrugsJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    ManufacturerEnterprise manufacturer;
    Drug drug;

    /**
     * Creates new form AddDrugsJPanel
     */
    public AddDrugsJPanel(JPanel userProcessContainer, ManufacturerEnterprise  manufacturer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.manufacturer = manufacturer;
        if(!manufacturer.getDrugCatalog().getDrugList().isEmpty()) {
            drugIDField.setText(String.valueOf(manufacturer.getDrugCatalog().getDrugList().size()+1));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddJPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblDrugID = new javax.swing.JLabel();
        drugIDField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        lblBrandName = new javax.swing.JLabel();
        brandNameField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        lblGenericName = new javax.swing.JLabel();
        genericNameField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setText("Add Drugs");
        AddJPanel.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        lblDrugID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDrugID.setText("Drug ID");
        AddJPanel.add(lblDrugID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 100, 30));

        drugIDField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        drugIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugIDFieldActionPerformed(evt);
            }
        });
        AddJPanel.add(drugIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 160, -1));

        backJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        AddJPanel.add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, -1));

        lblBrandName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBrandName.setText("Brand Name");
        AddJPanel.add(lblBrandName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 30));

        brandNameField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AddJPanel.add(brandNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 160, -1));

        saveButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        saveButton.setText("Add");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        AddJPanel.add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 100, 30));

        lblGenericName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblGenericName.setText("Generic Name");
        AddJPanel.add(lblGenericName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 110, 30));

        genericNameField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AddJPanel.add(genericNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 160, 30));

        add(AddJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 413, 479));
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        if(!Validate.validateTextField(brandNameField,lblBrandName ,0 ))
        {
            return;
        }
        if(!Validate.validateTextField(genericNameField,lblGenericName , 0))
        {
            return;
        }
        drug = manufacturer.getDrugCatalog().newDrug();
        drug.setBrandName(brandNameField.getText());
        drug.setGenericName(genericNameField.getText());
        drugIDField.setText(String.valueOf(manufacturer.getDrugCatalog().getDrugList().size()+1));

        JOptionPane.showMessageDialog(null, "Drug added");

        brandNameField.setText("");
        drugIDField.setText("");
        genericNameField.setText("");
    }//GEN-LAST:event_saveButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout)(userProcessContainer.getLayout());
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void drugIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drugIDFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddJPanel;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField brandNameField;
    private javax.swing.JTextField drugIDField;
    private javax.swing.JTextField genericNameField;
    private javax.swing.JLabel lblBrandName;
    private javax.swing.JLabel lblDrugID;
    private javax.swing.JLabel lblGenericName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
