/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DrugManager;

import Business.Business;
import Business.Drug;
import Business.Enterprise.Enterprise;
import Business.Enterprise.FDA;
import Business.Enterprise.ManufacturerEnterprise;
import Business.License;
import Business.Network.Network;
import Business.UserAccount;
import Business.WorkRequest.LicenseDrugWorkRequest;
import Business.WorkRequest.WorkRequest;
import Business.WorkRequest.WorkRequest.type;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Dhaval
 */
public class ManageDrugsJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    ManufacturerEnterprise manufacturer;
    Drug drug;
    Network network;
    UserAccount userAccount;

    /**
     * Creates new form ManageDrugsJPanel
     */
    public ManageDrugsJPanel(JPanel userProcessContainer,ManufacturerEnterprise manufacturer,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.manufacturer = manufacturer;
        this.userAccount =userAccount;
        network = (Network)Business.getInstance().getNetworkDirectory().searchUser(userAccount, Network.class.getSimpleName());
        Refresh();
    }
    private void Refresh(){
        int rowCount = directoryTable.getRowCount();
        for(int i = rowCount-1; i >= 0; i--)
        {
            ((DefaultTableModel)directoryTable.getModel()).removeRow(i);
        }
        if(!manufacturer.getDrugCatalog().getDrugList().isEmpty()) {
            for (Drug drug : manufacturer.getDrugCatalog().getDrugList())
            {
                Object row [] = new Object[3];
                row[0]= drug;
                row[1]=drug.getId();
                if(drug.getLicense()!=null)
                {
                    if(drug.getLicense().isLicensed())
                    {
                        row[2]= "Licensed";
                    }
                    else
                    {
                        row[2]= "License Requested";
                    }
                }
                else
                {
                    row[2] = "Not Licensed";
                }
                    ((DefaultTableModel)directoryTable.getModel()).addRow(row);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ManageJPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        directoryTable = new javax.swing.JTable();
        viewButton = new javax.swing.JButton();
        btnGetLicense = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        createButton1 = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(1, 0));

        ManageJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titleLabel.setText("Manage Drug");
        ManageJPanel.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        directoryTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        directoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "ID", "Licensed"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(directoryTable);

        ManageJPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 500, 110));

        viewButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        viewButton.setText("View Detail >>");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });
        ManageJPanel.add(viewButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 220, -1));

        btnGetLicense.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnGetLicense.setText("Get License");
        btnGetLicense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetLicenseActionPerformed(evt);
            }
        });
        ManageJPanel.add(btnGetLicense, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        searchButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchButton.setText("Search >>");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        ManageJPanel.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 130, -1));

        backButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        ManageJPanel.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 110, -1));

        refreshButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        refreshButton.setText("Refresh");
        refreshButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        refreshButton.setMargin(new java.awt.Insets(2, 1, 2, 1));
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });
        ManageJPanel.add(refreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 100, -1));

        createButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        createButton1.setText("Add ");
        createButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButton1ActionPerformed(evt);
            }
        });
        ManageJPanel.add(createButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        add(ManageJPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = directoryTable.getSelectedRow();
        if(selectedRow < 0 || selectedRow > directoryTable.getRowCount() )
        {
            JOptionPane.showMessageDialog(null,"Select a Row");
            return;}
        drug = (Drug)directoryTable.getValueAt(selectedRow, 0);
        ViewDrugsDetailJPanel vpdjp = new ViewDrugsDetailJPanel(userProcessContainer ,drug);
        userProcessContainer.add("ViewDrugDetail",vpdjp);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_viewButtonActionPerformed

    private void btnGetLicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetLicenseActionPerformed

        int selectedRow = directoryTable.getSelectedRow();
        FDA fda = null;
        if(selectedRow < 0 || selectedRow > directoryTable.getRowCount())
        {
            JOptionPane.showMessageDialog(null, "No row selected");
            return;
        }
        for(Enterprise e : network.getEnterpriseDirectory().geteList())
        {
            if(e.getEnterpriseName().equalsIgnoreCase("FDA"))
            {
                fda = (FDA)e;
            }
        }
        if(fda == null)
        {
            JOptionPane.showMessageDialog(null, "FDA not present");
            return;
        }
        Drug selectedDrug = (Drug)directoryTable.getValueAt(selectedRow, 0);
        selectedDrug.setLicense(new License());
        LicenseDrugWorkRequest request = (LicenseDrugWorkRequest)fda.getLicensingOrganization().getWorkQueue().newWorkRequest(type.RequestDrugLicense);
        request.setSender(userAccount);
        request.setDrug(selectedDrug);

        request.setStatus(WorkRequest.status.RequestedLicense);
        userAccount.getSendWorkQueue().addWorkRequest(request);
        JOptionPane.showMessageDialog(null, "Drug License Requested");
        Refresh();
    }//GEN-LAST:event_btnGetLicenseActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        SearchForDrugsJPanel sfpjp = new SearchForDrugsJPanel(userProcessContainer, manufacturer.getDrugCatalog());
        userProcessContainer.add("SearchForDrug",sfpjp);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_searchButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout)(userProcessContainer.getLayout());
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        Refresh();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void createButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButton1ActionPerformed
        // TODO add your handling code here:
        AddDrugsJPanel addDrugJPanel  = new AddDrugsJPanel(userProcessContainer,manufacturer);
        userProcessContainer.add("AddDrug",addDrugJPanel);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_createButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ManageJPanel;
    private javax.swing.JButton backButton;
    private javax.swing.JButton btnGetLicense;
    private javax.swing.JButton createButton1;
    private javax.swing.JTable directoryTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton viewButton;
    // End of variables declaration//GEN-END:variables
}
