/*
 * CreateDrugJPanel.java
 *
 * Created on September 18, 2008, 2:54 PM
 */
package UserInterface.DrugManager;

import Business.Drug;
import Business.Enterprise.DrugCatalog;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;



/**
 *
 * @author Dhaval
 */
public class SearchForDrugsJPanel extends javax.swing.JPanel {
JPanel userProcessContainer;
DrugCatalog drugCatalog;

    /** Creates new form CreateDrugJPanel */
    public SearchForDrugsJPanel(JPanel userProcessContainer,DrugCatalog drugCatalog) {

        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.drugCatalog = drugCatalog;

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleJLabel = new javax.swing.JLabel();
        idJLabel = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleJLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titleJLabel.setText("Search for Drugs");
        add(titleJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, 52));

        idJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        idJLabel.setText("Drug Id");
        add(idJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 116, -1, -1));

        idField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 145, 250, -1));

        searchButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchButton.setText("Search Now >>");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 144, 160, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        try{
            Integer.parseInt(idField.getText());
       }
        catch(NumberFormatException n)
        {
            JOptionPane.showMessageDialog(null, "Enter numeric value in ID field");
            idField.setText("");
            return;
        }
        Drug drug = drugCatalog.search(Integer.parseInt(idField.getText()));
        if(drug == null)
        {
            JOptionPane.showMessageDialog(null, "Drug not found");

        }
        else
        {
        ViewDrugsDetailJPanel vsdjp = new ViewDrugsDetailJPanel(userProcessContainer, drug);
        userProcessContainer.add("ViewDrugDetail",vsdjp);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
        }

}//GEN-LAST:event_searchButtonActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout)(userProcessContainer.getLayout());
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel idJLabel;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel titleJLabel;
    // End of variables declaration//GEN-END:variables
}
