/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DrugManager;

import Business.Address;
import Business.Drug;
import Business.Enterprise.DrugCatalog;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Dhaval
 */
public class ViewDrugsDetailJPanel extends javax.swing.JPanel {
Drug drug;
JPanel userProcessContainer;
DrugCatalog drugCatalog;
Address a;
    /**
     * Creates new form ViewDrugDetailJPanel
     */
    public ViewDrugsDetailJPanel(JPanel userProcessContainer,Drug drug) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.drug  = drug;
        saveButton.setVisible(false);

        brandNameField.setText(drug.getBrandName());
        drugIDField.setText(String.valueOf(drug.getId()));
        genericNameField.setText(String.valueOf(drug.getGenericName()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ViewJPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblDrugID = new javax.swing.JLabel();
        drugIDField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        lblBrandName = new javax.swing.JLabel();
        brandNameField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        lblGenericName = new javax.swing.JLabel();
        genericNameField = new javax.swing.JTextField();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        ViewJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setText("View Drug");
        ViewJPanel.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        lblDrugID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDrugID.setText("Drug ID");
        ViewJPanel.add(lblDrugID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 100, 30));

        drugIDField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        drugIDField.setEnabled(false);
        drugIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugIDFieldActionPerformed(evt);
            }
        });
        ViewJPanel.add(drugIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 160, -1));

        backJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        ViewJPanel.add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        lblBrandName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBrandName.setText("Brand Name");
        ViewJPanel.add(lblBrandName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 30));

        brandNameField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        brandNameField.setEnabled(false);
        ViewJPanel.add(brandNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 160, -1));

        saveButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        saveButton.setText("SAVE");
        saveButton.setEnabled(false);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        ViewJPanel.add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 70, 30));

        updateButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        updateButton.setText("Update Product");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        ViewJPanel.add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 176, -1));

        lblGenericName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblGenericName.setText("Generic Name");
        ViewJPanel.add(lblGenericName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 110, 30));

        genericNameField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        genericNameField.setEnabled(false);
        ViewJPanel.add(genericNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 160, 30));

        add(ViewJPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout)(userProcessContainer.getLayout());
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:

        drug.setBrandName(brandNameField.getText());
        drug.setGenericName(genericNameField.getText());
        saveButton.setVisible(false);
        updateButton.setVisible(true);

    }//GEN-LAST:event_saveButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        saveButton.setEnabled(true);
        saveButton.setVisible(true);
        updateButton.setVisible(false);
        brandNameField.setEnabled(true);
        genericNameField.setEnabled(true);

    }//GEN-LAST:event_updateButtonActionPerformed

    private void drugIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drugIDFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ViewJPanel;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField brandNameField;
    private javax.swing.JTextField drugIDField;
    private javax.swing.JTextField genericNameField;
    private javax.swing.JLabel lblBrandName;
    private javax.swing.JLabel lblDrugID;
    private javax.swing.JLabel lblGenericName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
