/*
 * ProductManagerWorkAreaJPanel.java
 *
 * Created on October 3, 2008, 8:06 AM
 */
package UserInterface.PatientRole;

import Business.UserAccount;
import UserInterface.BusinessAdmin.*;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Dhaval
 */
public class PatientWorkAreaJPanel extends javax.swing.JPanel {
JPanel userProcessContainer;
UserAccount user;
    /** Creates new form ProductManagerWorkAreaJPanel */
    public PatientWorkAreaJPanel(JPanel userProcessContainer, UserAccount user) {

        initComponents();
        lblWelcome.setText("Welcome : Business Admin");
        this.userProcessContainer  = userProcessContainer;
        this.user = user;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnReportDrug = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setText("Patient Work Area");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        btnReportDrug.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnReportDrug.setText("Report Drug");
        btnReportDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportDrugActionPerformed(evt);
            }
        });
        add(btnReportDrug, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 118, -1, -1));

        lblWelcome.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblWelcome.setText("WELCOME");
        add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 250, 20));
    }// </editor-fold>//GEN-END:initComponents
    private void btnReportDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportDrugActionPerformed
        // TODO add your handling code here:
        ManageNetworkJPanel mnjp =new ManageNetworkJPanel(userProcessContainer,user);
        userProcessContainer.add("Manage network",mnjp);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);

    }//GEN-LAST:event_btnReportDrugActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReportDrug;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
