/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PatientRole;

import Business.Business;
import Business.Drug;
import Business.Enterprise.DrugCatalog;
import Business.Enterprise.Enterprise;
import Business.Enterprise.ManufacturerEnterprise;
import Business.Network.Network;
import Business.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dhaval
 */
public class ReportSuspectDrugJPanel extends javax.swing.JPanel {
JPanel userProcessContainer;
DrugCatalog drugCatalog;
Drug drug;
ManufacturerEnterprise manufacturer;
ArrayList<Enterprise> enterpriseList;
Network network;
UserAccount userAccount;
    /**
     * Creates new form AddDrugJPanel
     */
////////////    public ReportSuspectDrugJPanel(JPanel userProcessContainer, UserAccount userAccount) {
////////////        initComponents();
////////////        this.userProcessContainer = userProcessContainer;
////////////        this.userAccount = userAccount;
////////////        network = Business.getInstance().getNetworkDirectory().findNetwork(userAccount);
////////////        enterpriseList = network.getEnterpriseDirectory().geteList();
////////////        suppJComboBox.removeAll();
////////////        for(Enterprise enterprise : enterpriseList)
////////////        {
////////////            if(enterprise.getType().equals(Enterprise.MANUFACTURER))
////////////            {
////////////                suppJComboBox.addItem(enterprise);
////////////            }
////////////        }
////////////    }
////////////
////////////        private void Refresh(){
////////////        int rowCount = drugTable.getRowCount();
////////////        for(int i = rowCount-1; i >= 0; i--)
////////////        {
////////////            ((DefaultTableModel)drugTable.getModel()).removeRow(i);
////////////        }
////////////        manufacturer = (ManufacturerEnterprise)suppJComboBox.getSelectedItem();
////////////        for (Drug drug : manufacturer.getDrugCatalog().getDrugList())
////////////        {
////////////            if(drug.getLicense().isStatus())
////////////            {
////////////                Object row [] = new Object[6];
////////////                row[0]=drug;
////////////                row[1]=drug.getId();
////////////                row[2]=drug.getDrugType();
////////////                row[3]=drug.getDrugSubstance();
////////////                row[4]=drug.getManufactureDate();
////////////                row[5] = drug.getExpiryDate();
////////////
////////////                ((DefaultTableModel)drugTable.getModel()).addRow(row);
////////////            }
////////////        }
////////////    }
////////////
////////////    /**
////////////     * This method is called from within the constructor to initialize the form.
////////////     * WARNING: Do NOT modify this code. The content of this method is always
////////////     * regenerated by the Form Editor.
////////////     */
////////////    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        reportDrugJLabel = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        reportDrugJButton = new javax.swing.JButton();
        suppJComboBox = new javax.swing.JComboBox();
        commentsJLabel = new javax.swing.JLabel();
        drugCatalogJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        drugTable = new javax.swing.JTable();
        symptomsJLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        symptomsJTextArea = new javax.swing.JTextArea();
        effectsJLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        effectsJTextArea = new javax.swing.JTextArea();
        selectManufacturerJLabel3 = new javax.swing.JLabel();
        selectManufacturerJLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        commentsJTextArea = new javax.swing.JTextArea();

        jLabel12.setText("jLabel12");

        jTextField11.setText("jTextField11");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reportDrugJLabel.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        reportDrugJLabel.setText("Report Drug");
        add(reportDrugJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        backJButton.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        backJButton.setText("BACK");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 567, -1, -1));

        reportDrugJButton.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        reportDrugJButton.setText("Report Drug ");
        reportDrugJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportDrugJButtonActionPerformed(evt);
            }
        });
        add(reportDrugJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 567, -1, -1));

        suppJComboBox.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        suppJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppJComboBoxActionPerformed(evt);
            }
        });
        add(suppJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 150, -1));

        commentsJLabel.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        commentsJLabel.setText("Comments");
        add(commentsJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 490, 121, 30));

        drugCatalogJLabel.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        drugCatalogJLabel.setText("Drug Catalog");
        add(drugCatalogJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 126, 160, -1));

        drugTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Drug ID", "Drug Type", "Drug Substance", "Manufacture Date", "Expiry Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        drugTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                drugTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(drugTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 166, 729, 100));

        symptomsJLabel.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        symptomsJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        symptomsJLabel.setText("Symptoms before consuming the drug");
        add(symptomsJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 325, 300, 30));

        symptomsJTextArea.setColumns(20);
        symptomsJTextArea.setRows(5);
        jScrollPane2.setViewportView(symptomsJTextArea);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 270, 80));

        effectsJLabel.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        effectsJLabel.setText("Adverse Effects after drug consumption");
        add(effectsJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 310, 30));

        effectsJTextArea.setColumns(20);
        effectsJTextArea.setRows(5);
        jScrollPane3.setViewportView(effectsJTextArea);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 382, 270, 80));

        selectManufacturerJLabel3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        selectManufacturerJLabel3.setText("Fill if applicable");
        add(selectManufacturerJLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 284, 143, 35));

        selectManufacturerJLabel4.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        selectManufacturerJLabel4.setText("Select Manufacturer");
        add(selectManufacturerJLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 86, 170, 30));

        commentsJTextArea.setColumns(20);
        commentsJTextArea.setRows(5);
        jScrollPane4.setViewportView(commentsJTextArea);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 471, 270, 80));
    }// </editor-fold>//GEN-END:initComponents
    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void reportDrugJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportDrugJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = drugTable.getSelectedRow();
        if(selectedRow < 0 || selectedRow > drugTable.getRowCount())
        {
            JOptionPane.showMessageDialog(null, "No row selected");
            return;
        }
        Drug selectedDrug = (Drug)drugTable.getValueAt(selectedRow, 0);

//        drug = manufacturer.getDrugCatalog().newDrug();
//        drug.setDrugName(drugNameJTextField.getText());
//        drug.setDrugType(drugTypeJTextField.getText());
//        drug.setDrugDosage(drugDosageJTextField.getText());
//        drug.setDrugSubstance(drugSubstanceJTextField.getText());
//
//        drugNameJTextField.setText("");
//        drugTypeJTextField.setText("");
//        drugDosageJTextField.setText("");
//        drugSubstanceJTextField.setText("");


    }//GEN-LAST:event_reportDrugJButtonActionPerformed

    private void suppJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppJComboBoxActionPerformed
        // TODO add your handling code here:
        //Refresh();
    }//GEN-LAST:event_suppJComboBoxActionPerformed

    private void drugTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drugTableMouseClicked
        // TODO add your handling code here:
        int selectedRow = drugTable.getSelectedRow();
        if(selectedRow < 0 || selectedRow > drugTable.getRowCount())
        {
            JOptionPane.showMessageDialog(null, "No row selected");
            return;
        }
        Drug selectedDrug = (Drug)drugTable.getValueAt(selectedRow, 0);
//        salepriceJComboBox.removeAllItems();
//        salepriceJComboBox.addItem(selectedDrug.getFloorPrice());
//        salepriceJComboBox.addItem(selectedDrug.getActualPrice());
//        salepriceJComboBox.addItem(selectedDrug.getCeilingPrice());
    }//GEN-LAST:event_drugTableMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel commentsJLabel;
    private javax.swing.JTextArea commentsJTextArea;
    private javax.swing.JLabel drugCatalogJLabel;
    private javax.swing.JTable drugTable;
    private javax.swing.JLabel effectsJLabel;
    private javax.swing.JTextArea effectsJTextArea;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JButton reportDrugJButton;
    private javax.swing.JLabel reportDrugJLabel;
    private javax.swing.JLabel selectManufacturerJLabel3;
    private javax.swing.JLabel selectManufacturerJLabel4;
    private javax.swing.JComboBox suppJComboBox;
    private javax.swing.JLabel symptomsJLabel;
    private javax.swing.JTextArea symptomsJTextArea;
    // End of variables declaration//GEN-END:variables
}
