/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.InventoryManager;

import Business.Business;
import Business.Drug;
import Business.Enterprise.Enterprise;
import Business.Enterprise.ManufacturerEnterprise;
import Business.InventoryItem;
import Business.Network.Network;
import Business.UserAccount;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dhaval
 */
public class AddInventoryJPanel extends javax.swing.JPanel {
JPanel userProcessContainer;
Drug selectedDrug;
InventoryItem inventoryItem;
ManufacturerEnterprise enterprise;
UserAccount userAccount;
ArrayList<Drug> drugList;
Network network;
ManufacturerEnterprise manufacturer;
    /**
     * Creates new form ManageInventoryJPanel
     */
    public AddInventoryJPanel(JPanel userProcessContainer, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        manufacturer=(ManufacturerEnterprise)Business.getInstance().getNetworkDirectory().searchUser(userAccount, Enterprise.class.getSimpleName());
        refreshDrugJTable();
    }

    private void refreshDrugJTable()
    {
        int rowCount = drugJTable.getRowCount();
        DefaultTableModel model = (DefaultTableModel)drugJTable.getModel();
        for(int i=rowCount-1; i>=0; --i)
        {
            model.removeRow(i);
        }

        drugList = manufacturer.getDrugCatalog().getDrugList();
        for(Drug drug: drugList)
        {
            Object row[] = new Object[2];
            row[0] = drug;
            row[1] = drug.getId();

            model.addRow(row);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        drugJTable = new javax.swing.JTable();
        drugCatalogJLabel = new javax.swing.JLabel();
        backjButton = new javax.swing.JButton();
        addJButton = new javax.swing.JButton();
        quantityJSpinner = new javax.swing.JSpinner();
        quantityJLabel = new javax.swing.JLabel();
        expireJLabel = new javax.swing.JLabel();
        expireJTextField = new javax.swing.JTextField();
        floorPriceJLabel = new javax.swing.JLabel();
        actualPriceJTextField = new javax.swing.JTextField();
        actualPriceJLabel = new javax.swing.JLabel();
        floorPriceJTextField = new javax.swing.JTextField();
        ceilingPriceJLabel = new javax.swing.JLabel();
        ceilingPriceJTextField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        drugJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug Name", "Drug Id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(drugJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 57, 340, 80));

        drugCatalogJLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        drugCatalogJLabel.setText("Drug Catalog");
        add(drugCatalogJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 10, 169, -1));

        backjButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backjButton.setText("Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });
        add(backjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 454, -1, -1));

        addJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addJButton.setText("Add Drug");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });
        add(addJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 412, -1, -1));

        quantityJSpinner.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        quantityJSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        add(quantityJSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 163, 50, 30));

        quantityJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        quantityJLabel.setText("Quantity:");
        add(quantityJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 167, -1, -1));

        expireJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        expireJLabel.setText("Expire in how many months");
        add(expireJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 228, -1, -1));

        expireJTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(expireJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 225, 90, -1));

        floorPriceJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        floorPriceJLabel.setText("Floor Price");
        add(floorPriceJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 270, -1, -1));

        actualPriceJTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(actualPriceJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 313, 90, -1));

        actualPriceJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        actualPriceJLabel.setText("Actual Price");
        add(actualPriceJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 316, -1, -1));

        floorPriceJTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(floorPriceJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 267, 90, -1));

        ceilingPriceJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ceilingPriceJLabel.setText("Ceiling Price");
        add(ceilingPriceJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 355, -1, -1));

        ceilingPriceJTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(ceilingPriceJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 352, 90, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed
        // TODO add your handling code here:
        inventoryItem = manufacturer.getInventoryCatalog().newInventoryItem();
            int quantity = (Integer)quantityJSpinner.getValue();
            if(quantity <=0)
            {
            return;
            }

        int selectedIndex = drugJTable.getSelectedRow();
        if(selectedIndex < 0)
        {
            return;
        }

//        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
//        Calendar c = Calendar.getInstance();
//        c.setTime(new Date()); // Now use today date.
//        c.add(Calendar.YEAR, 5); // Adding 5 days
//        license.setValidTill(c.getTime());

        SimpleDateFormat sdf = new SimpleDateFormat("MM-dd-yy");
        Date date = new Date();
        Calendar c = Calendar.getInstance();
        c.setTime(new Date());
        String cdate = sdf.format(date);

        Drug drug = (Drug)drugJTable.getValueAt(selectedIndex, 0);
        inventoryItem = manufacturer.getInventoryCatalog().findItem(drug);
        if(inventoryItem == null)
        {
            inventoryItem = manufacturer.getInventoryCatalog().newInventoryItem();
        }
        inventoryItem.setAvail(quantity);
        drug.setActualPrice(Integer.parseInt(actualPriceJTextField.getText()));
        drug.setCeilingPrice(Integer.parseInt(ceilingPriceJTextField.getText()));
        drug.setFloorPrice(Integer.parseInt(floorPriceJTextField.getText()));
        c.add(Calendar.MONTH, Integer.parseInt(expireJTextField.getText()));
        inventoryItem.setExpiryDate(c.getTime());
        inventoryItem.setManufactureDate(date);
        inventoryItem.setDrug(drug);




    }//GEN-LAST:event_addJButtonActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actualPriceJLabel;
    private javax.swing.JTextField actualPriceJTextField;
    private javax.swing.JButton addJButton;
    private javax.swing.JButton backjButton;
    private javax.swing.JLabel ceilingPriceJLabel;
    private javax.swing.JTextField ceilingPriceJTextField;
    private javax.swing.JLabel drugCatalogJLabel;
    private javax.swing.JTable drugJTable;
    private javax.swing.JLabel expireJLabel;
    private javax.swing.JTextField expireJTextField;
    private javax.swing.JLabel floorPriceJLabel;
    private javax.swing.JTextField floorPriceJTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel quantityJLabel;
    private javax.swing.JSpinner quantityJSpinner;
    // End of variables declaration//GEN-END:variables
}
