/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BusinessAdminWorkAreaJPanel.java
 *
 * Created on Nov 2, 2012, 5:59:07 PM
 */
package UserInterface.InventoryManager;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount;
import Business.WorkRequest.*;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dhaval
 */
public class InventoryManagerWorkQueueJPanel extends javax.swing.JPanel {

    //private Enterprise enterprise;
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;

    /** Creates new form BusinessAdminWorkAreaJPanel */
    public InventoryManagerWorkQueueJPanel(JPanel upc, Enterprise ent, UserAccount ua) {
        initComponents();

        enterprise = ent;
        userProcessContainer = upc;
        userAccount = ua;
        refreshWorkRequestTable();
    }
    private void refreshWorkRequestTable()
    {
        int r = queueJTable.getRowCount();
        DefaultTableModel m = (DefaultTableModel)queueJTable.getModel();

        for(int  i = r-1;i>=0;i--)
        {
            m.removeRow(i);
        }
        Organization o = enterprise.getOrganizationDirectory().searchUserOrganization(userAccount);
        for(WorkRequest w : o.getWorkQueue().getQueue())
        {
            Object row[] = new Object[4];
            row[0]= w;
            row[1]= w.getSender();
            row[2]= w.getReceiver();
            row[3]= w.getStatus().toString();

            m.addRow(row);
        }

    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnMyQueue = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        queueJTable = new javax.swing.JTable();
        btnWorkOnIt = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setText("Inventory Manager Organization Queue");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 480, -1));

        btnMyQueue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMyQueue.setText("Add to my Work Queue");
        btnMyQueue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyQueueActionPerformed(evt);
            }
        });
        add(btnMyQueue, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 260, -1));

        queueJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Type", "Sender", "Receiver", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        queueJTable.setName(""); // NOI18N
        jScrollPane1.setViewportView(queueJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 570, 95));

        btnWorkOnIt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnWorkOnIt.setText("Work on it");
        btnWorkOnIt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorkOnItActionPerformed(evt);
            }
        });
        add(btnWorkOnIt, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 210, -1));

        backJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 80, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnMyQueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyQueueActionPerformed
        // TODO add your handling code here:
        int r = queueJTable.getSelectedRow();
        if(r<0)
        {
            return;
        }
        ReceiveShippmentWorkRequest req = (ReceiveShippmentWorkRequest)queueJTable.getValueAt(r, 0);
        req.setReceiver(userAccount);

        JOptionPane.showMessageDialog(null, "Added to my work queue");
        refreshWorkRequestTable();

    }//GEN-LAST:event_btnMyQueueActionPerformed

    private void btnWorkOnItActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkOnItActionPerformed
        // TODO add your handling code here:
        int r = queueJTable.getSelectedRow();
        if(r<0)
        {
            return;
        }
        WorkRequest req = (WorkRequest)queueJTable.getValueAt(r, 0);
        if(req.getReceiver()== userAccount )
        {
            JPanel panel = new WorkOnRequestJPanel(userProcessContainer, (ReceiveShippmentWorkRequest)req, userAccount);
            userProcessContainer.add("WorkOnRequestJPanel", panel);
            CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
            cardLayout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnWorkOnItActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnMyQueue;
    private javax.swing.JButton btnWorkOnIt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable queueJTable;
    // End of variables declaration//GEN-END:variables
}
