/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.InventoryManager;

import Business.Address;
import Business.Drug;
import Business.Enterprise.DrugCatalog;
import Business.InventoryItem;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Dhaval
 */
public class ViewDrugsDetailJPanel extends javax.swing.JPanel {
Drug drug;
JPanel userProcessContainer;
DrugCatalog drugCatalog;
Address a;
InventoryItem inventoryItem;
    /**
     * Creates new form ViewDrugDetailJPanel
     */
    public ViewDrugsDetailJPanel(JPanel userProcessContainer,InventoryItem inventoryItem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.inventoryItem = inventoryItem;
        saveButton.setVisible(false);

        brandNameField.setText(drug.getBrandName());
        drugIDField.setText(String.valueOf(drug.getId()));
        actualPriceField.setText(String.valueOf(drug.getActualPrice()));
        floorPriceField.setText(String.valueOf(drug.getFloorPrice()));
        ceilingPriceField.setText(String.valueOf(drug.getCeilingPrice()));
        manuDateJXDatePicker.setDate(inventoryItem.getManufactureDate());
        expiryDateJXDatePicker.setDate(inventoryItem.getExpiryDate());
        genericNameField.setText(String.valueOf(drug.getGenericName()));
        batchIDField.setText(String.valueOf(inventoryItem.getBatchID()));


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ViewJPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblDrugID = new javax.swing.JLabel();
        drugIDField = new javax.swing.JTextField();
        lblActualPrice = new javax.swing.JLabel();
        actualPriceField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        lblBrandName = new javax.swing.JLabel();
        brandNameField = new javax.swing.JTextField();
        lblFloorPrice = new javax.swing.JLabel();
        floorPriceField = new javax.swing.JTextField();
        ceilingPriceField = new javax.swing.JTextField();
        lblCeilingPrice = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        lblManufactureDate = new javax.swing.JLabel();
        lblExpiryDate = new javax.swing.JLabel();
        lblGenericName = new javax.swing.JLabel();
        lblBatchID = new javax.swing.JLabel();
        batchIDField = new javax.swing.JTextField();
        genericNameField = new javax.swing.JTextField();
        manuDateJXDatePicker = new org.jdesktop.swingx.JXDatePicker();
        expiryDateJXDatePicker = new org.jdesktop.swingx.JXDatePicker();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        ViewJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setText("View Drug");
        ViewJPanel.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        lblDrugID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDrugID.setText("Drug ID");
        ViewJPanel.add(lblDrugID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 100, 30));

        drugIDField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        drugIDField.setEnabled(false);
        drugIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugIDFieldActionPerformed(evt);
            }
        });
        ViewJPanel.add(drugIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 160, -1));

        lblActualPrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblActualPrice.setText("Actual Price");
        ViewJPanel.add(lblActualPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 110, 30));

        actualPriceField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        actualPriceField.setEnabled(false);
        ViewJPanel.add(actualPriceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 160, 30));

        backJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        ViewJPanel.add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, -1));

        lblBrandName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBrandName.setText("Brand Name");
        ViewJPanel.add(lblBrandName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, 30));

        brandNameField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        brandNameField.setEnabled(false);
        ViewJPanel.add(brandNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 160, -1));

        lblFloorPrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFloorPrice.setText("Floor Price");
        ViewJPanel.add(lblFloorPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 110, 30));

        floorPriceField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        floorPriceField.setEnabled(false);
        ViewJPanel.add(floorPriceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 160, 30));

        ceilingPriceField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ceilingPriceField.setEnabled(false);
        ViewJPanel.add(ceilingPriceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 160, 30));

        lblCeilingPrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCeilingPrice.setText("Ceiling Price");
        ViewJPanel.add(lblCeilingPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 110, 30));

        saveButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        saveButton.setText("SAVE");
        saveButton.setEnabled(false);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        ViewJPanel.add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 70, 30));

        updateButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        updateButton.setText("Update Product");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        ViewJPanel.add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 176, -1));

        lblManufactureDate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblManufactureDate.setText("Manufacture Date");
        ViewJPanel.add(lblManufactureDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, 30));

        lblExpiryDate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblExpiryDate.setText("Expiry Date");
        ViewJPanel.add(lblExpiryDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 100, 30));

        lblGenericName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblGenericName.setText("Generic Name");
        ViewJPanel.add(lblGenericName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 110, 30));

        lblBatchID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBatchID.setText("Batch ID");
        ViewJPanel.add(lblBatchID, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 110, 30));

        batchIDField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        batchIDField.setEnabled(false);
        ViewJPanel.add(batchIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 160, 30));

        genericNameField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        genericNameField.setEnabled(false);
        ViewJPanel.add(genericNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 160, 30));
        ViewJPanel.add(manuDateJXDatePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 160, -1));
        ViewJPanel.add(expiryDateJXDatePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 160, -1));

        add(ViewJPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout)(userProcessContainer.getLayout());
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        try{
            Integer.parseInt(actualPriceField.getText());
        }
        catch(NumberFormatException n)
        {
            JOptionPane.showMessageDialog(null, "Enter numeric value in Actual Price field");
            actualPriceField.setText("");
           return;
        }
        try{
            Integer.parseInt(floorPriceField.getText());
        }
        catch(NumberFormatException n)
        {
            JOptionPane.showMessageDialog(null, "Enter numeric value in Floor Price field");
            floorPriceField.setText("");
            return;
        }
        try{
            Integer.parseInt(ceilingPriceField.getText());
        }
        catch(NumberFormatException n)
        {
            JOptionPane.showMessageDialog(null, "Enter numeric value in Ceiling Price field");
            ceilingPriceField.setText("");
            return;
        }

        try{
            Integer.parseInt(batchIDField.getText());
       }
        catch(NumberFormatException n)
        {
            JOptionPane.showMessageDialog(null, "Enter numeric value in Batch ID field");
            batchIDField.setText("");
            return;
        }
        drug.setBrandName(brandNameField.getText());
        drug.setGenericName(genericNameField.getText());
        drug.setActualPrice(Integer.parseInt(actualPriceField.getText()));
        drug.setFloorPrice(Integer.parseInt(floorPriceField.getText()));
        drug.setCeilingPrice(Integer.parseInt(ceilingPriceField.getText()));
        inventoryItem.setManufactureDate(manuDateJXDatePicker.getDate());
        inventoryItem.setExpiryDate(expiryDateJXDatePicker.getDate());
        inventoryItem.setBatchID(Integer.parseInt(batchIDField.getText()));


        saveButton.setVisible(false);
        updateButton.setVisible(true);

    }//GEN-LAST:event_saveButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        saveButton.setEnabled(true);
        saveButton.setVisible(true);
        updateButton.setVisible(false);
        brandNameField.setEnabled(true);
        actualPriceField.setEnabled(true);
        ceilingPriceField.setEnabled(true);
        batchIDField.setEnabled(true);
        floorPriceField.setEnabled(true);
        expiryDateJXDatePicker.setEnabled(true);
        genericNameField.setEnabled(true);
        manuDateJXDatePicker.setEnabled(true);

    }//GEN-LAST:event_updateButtonActionPerformed

    private void drugIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drugIDFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ViewJPanel;
    private javax.swing.JTextField actualPriceField;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField batchIDField;
    private javax.swing.JTextField brandNameField;
    private javax.swing.JTextField ceilingPriceField;
    private javax.swing.JTextField drugIDField;
    private org.jdesktop.swingx.JXDatePicker expiryDateJXDatePicker;
    private javax.swing.JTextField floorPriceField;
    private javax.swing.JTextField genericNameField;
    private javax.swing.JLabel lblActualPrice;
    private javax.swing.JLabel lblBatchID;
    private javax.swing.JLabel lblBrandName;
    private javax.swing.JLabel lblCeilingPrice;
    private javax.swing.JLabel lblDrugID;
    private javax.swing.JLabel lblExpiryDate;
    private javax.swing.JLabel lblFloorPrice;
    private javax.swing.JLabel lblGenericName;
    private javax.swing.JLabel lblManufactureDate;
    private javax.swing.JLabel lblTitle;
    private org.jdesktop.swingx.JXDatePicker manuDateJXDatePicker;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
