/*
 * CreateProductJPanel.java
 *
 * Created on September 18, 2008, 2:54 PM
 */
package UserInterface.NetworkAdmin;

import Business.Enterprise.Enterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Dhaval
 */
public class ViewAdminJPanel extends javax.swing.JPanel {
JPanel userProcessContainer;
Enterprise enterprise;


    /** Creates new form CreateProductJPanel */
    public ViewAdminJPanel(JPanel userProcessContainer,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        txtName.setText(enterprise.getEnterpriseName());
        if(!enterprise.getEd().geteList().isEmpty())
        {
            txtAdminName.setText(enterprise.getEd().geteList().get(0).getPerson().getfName());
        }




   }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbllTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblAdminName = new javax.swing.JLabel();
        txtAdminName = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbllTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbllTitle.setText("View Admin");
        add(lbllTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 19, -1, -1));

        lblName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblName.setText("Enterprise Name:");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 30));

        txtName.setEditable(false);
        txtName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtName.setEnabled(false);
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 159, 30));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 290, -1, -1));

        lblAdminName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAdminName.setText("Admin Name");
        add(lblAdminName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 138, -1, 30));

        txtAdminName.setEditable(false);
        txtAdminName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtAdminName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtAdminName.setEnabled(false);
        add(txtAdminName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 138, 159, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout)(userProcessContainer.getLayout());
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblAdminName;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lbllTitle;
    private javax.swing.JTextField txtAdminName;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
